version: '3.8'

services:
  flowise:
    image: flowiseai/flowise
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - FLOWISE_USERNAME=user
      - FLOWISE_PASSWORD=password
    volumes:
      - ~/.flowise:/root/.flowise
    restart: always
